Repository PrestaShop/pagesnotfound, pull requests merged in 2022-01, with the labels that each got.

#20 Add build release
  .github/workflows/build-release.yml
Labels: enhancement

#19 Release 2.0.2
  .github/workflows/build-release.yml
  config.xml
  pagesnotfound.php
  upgrade/upgrade-2.0.2.php
Labels: enhancement, QA ✔️

#21 Set tab property
  pagesnotfound.php
Labels: bug
